<?php get_header();?>

<div class="ajax-overlay">
	<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
		style="margin: auto; display: block; shape-rendering: auto;" width="231px" height="231px" viewBox="0 0 100 100"
		preserveAspectRatio="xMidYMid">
		<g transform="rotate(0 50 50)">
			<rect x="46.5" y="29.5" rx="3.5" ry="3.5" width="7" height="7" fill="#feb326">
				<animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.2048192771084336s"
					begin="-1.07095046854083s" repeatCount="indefinite"></animate>
			</rect>
		</g>
		<g transform="rotate(40 50 50)">
			<rect x="46.5" y="29.5" rx="3.5" ry="3.5" width="7" height="7" fill="#f66f8d">
				<animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.2048192771084336s"
					begin="-0.9370816599732261s" repeatCount="indefinite"></animate>
			</rect>
		</g>
		<g transform="rotate(80 50 50)">
			<rect x="46.5" y="29.5" rx="3.5" ry="3.5" width="7" height="7" fill="#6f459e">
				<animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.2048192771084336s"
					begin="-0.8032128514056224s" repeatCount="indefinite"></animate>
			</rect>
		</g>
		<g transform="rotate(120 50 50)">
			<rect x="46.5" y="29.5" rx="3.5" ry="3.5" width="7" height="7" fill="#64c5eb">
				<animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.2048192771084336s"
					begin="-0.6693440428380187s" repeatCount="indefinite"></animate>
			</rect>
		</g>
		<g transform="rotate(160 50 50)">
			<rect x="46.5" y="29.5" rx="3.5" ry="3.5" width="7" height="7" fill="#8cbd61">
				<animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.2048192771084336s"
					begin="-0.535475234270415s" repeatCount="indefinite"></animate>
			</rect>
		</g>
		<g transform="rotate(200 50 50)">
			<rect x="46.5" y="29.5" rx="3.5" ry="3.5" width="7" height="7" fill="#feb326">
				<animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.2048192771084336s"
					begin="-0.4016064257028112s" repeatCount="indefinite"></animate>
			</rect>
		</g>
		<g transform="rotate(240 50 50)">
			<rect x="46.5" y="29.5" rx="3.5" ry="3.5" width="7" height="7" fill="#f66f8d">
				<animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.2048192771084336s"
					begin="-0.2677376171352075s" repeatCount="indefinite"></animate>
			</rect>
		</g>
		<g transform="rotate(280 50 50)">
			<rect x="46.5" y="29.5" rx="3.5" ry="3.5" width="7" height="7" fill="#6f459e">
				<animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.2048192771084336s"
					begin="-0.13386880856760375s" repeatCount="indefinite"></animate>
			</rect>
		</g>
		<g transform="rotate(320 50 50)">
			<rect x="46.5" y="29.5" rx="3.5" ry="3.5" width="7" height="7" fill="#64c5eb">
				<animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1.2048192771084336s" begin="0s"
					repeatCount="indefinite"></animate>
			</rect>
		</g>
		<!-- [ldio] generated by https://loading.io/ -->
	</svg>
</div>
<div class="container">
	<div class="breadcrumbs" typeof="BreadcrumbList" vocab="https://schema.org/">
		<?php if (function_exists('bcn_display')) {
	bcn_display();
}?>
	</div>
</div>

<?php $termID       = get_queried_object()->term_id;?>
<?php $termchildren = get_term_children($termID, 'library_type');?>

<?php if ($termchildren) {?>
<section class="lib container">
	<div class="g-title g-title--1 turquoise" data-aos="title-animation">
		<h2><span><?php single_term_title();?> </span></h2>
	</div>

	<div class="lib-tiles">
		<div class="lib-tiles__wr">
			<?php foreach ($termchildren as $library_type_item) {?>
			<div class="lib-tiles__item">
				<a href="<?php echo get_bloginfo('url') . '/library_type/' . get_term($library_type_item)->slug . '/'; ?>"
					style="color:<?php the_field('czvet_ramki_i_teksta', $library_type_item);?>">
					<div class="lib-tiles__img"
						style="border-color:<?php the_field('czvet_ramki_i_teksta', get_term($library_type_item));?>">
						<?php $img = get_field('izobrazhenie', get_term($library_type_item));?>
						<?php echo wp_get_attachment_image($img['ID'], '300x300'); ?>
					</div>
					<h2><?php echo get_term($library_type_item)->name; ?></h2>
				</a>
			</div>
			<?php }?>
		</div>
	</div>
</section>
<?php } else {?>

<div class="container">
	<div class="g-title g-title--1 turquoise" data-aos="title-animation">
		<h2><span><?php single_term_title();?> </span></h2>
	</div>
	<?php echo do_shortcode('[wd_asp id=4]'); ?>
	<?php if (get_field('zagolovok_spojlera', get_queried_object())): ?>
	<div class="lib-spoiler">
		<div class="lib-spoiler__title">
			<?php echo get_field('zagolovok_spojlera', get_queried_object()); ?>
		</div>
		<?php if (get_field('tekst_spojlera', get_queried_object())): ?>
		<div class="lib-spoiler__body">
			<?php echo get_field('tekst_spojlera', get_queried_object()); ?>
		</div>
		<?php endif;?>
	</div>
	<?php endif;?>



	<div class="books__wr">

		<div class="books__items">

			<div id="response">

				<?php $args  = array(
					'post_type' => 'privetboock', 
					'posts_per_page' => 2, 
					'orderby' => 'name', // we will sort posts by date
					'order'	=> $_POST['name'], // ASC or DESC
					'paged' => (get_query_var('paged') ? get_query_var('paged') : 1));?>
				<?php $query = new WP_Query($args);?>
				<div class="libery__row">

					<?php if ($query->have_posts()): ?>
					<?php $i = 0;?>
					<?php while ($query->have_posts()): $query->the_post();?>
					<?php $i++;?>
					<?php $complexity               = get_the_terms($post->ID, 'complexity');?>
					<?php $loop                     = get_the_terms($post->ID, 'loop');?>
					<?php $interesting_for_children = get_the_terms($post->ID, 'interesting_for_children');?>



					<section
						class="lib-box <?php foreach ($complexity as $term) {echo $term->slug . ' ';}?><?php foreach ($loop as $term) {echo $term->slug . ' ';}?><?php foreach ($interesting_for_children as $term) {echo $term->slug . ' ';}?>"
						data-aos="books-amin" data-aos-offset="-500" data-aos-delay="<?php echo $i . '00'; ?>">
						<div class="lib-box__img">
							<?php the_post_thumbnail(['200', '999', true]);?>
						</div>
						<div class="lib-box__info">

							<?php $chitaem = get_field('chitaem_v_chitaj_klube');?>
							<div class="lib-box__text <?php if ($chitaem) {echo 'has-read-label';}?>">
								<?php if ($chitaem) {?>
								<div class="read-in-club">
									<img src="<?php bloginfo('template_url');?>/img/read-in-club.png" alt="">
								</div>
								<?php }?>

								<h2><?php the_title();?></h2>
								<p><b>Автор:</b>
									<?php $avtor = get_the_terms($post->ID, 'avtor');?>
									<?php foreach ($avtor as $term): ?>
									<span><?php echo $term->name; ?></span>
									<?php endforeach;?>
								</p>
								<p><b>Сложность чтения:</b>
									<?php foreach ($complexity as $term): ?>
									<span><?php echo $term->name; ?></span>
									<?php endforeach;?>
								</p>
								<p>
									<b>Цикл:</b>
									<?php foreach ($loop as $term): ?>
									<span><?php echo $term->name; ?></span>
									<?php endforeach;?>
								</p>
								<p>
									<b>Интересно детям:</b>
									<?php foreach ($interesting_for_children as $term): ?>
									<span><?php echo $term->name; ?></span>
									<?php endforeach;?>
								</p>
								<div class="lib-excerpt">
									<div class="short">
										<?php $the_excerpt = get_the_excerpt();?>
										<?php echo mb_substr($the_excerpt, 0, 250); ?>
										<span>... ⋙</span>
									</div>
									<div class="long"><?php the_excerpt();?>
										<span> ⋘</span>
									</div>


								</div>
								<div class="lib-box__tags">
									<?php $tags = get_the_terms($post->ID, 'tags');?>
									<?php foreach ($tags as $term): ?>
									<a href="<?php echo get_bloginfo('url') . '/tags/' . $term->slug; ?>"><?php echo $term->name; ?></a>
									<?php endforeach;?>
								</div>
							</div>
							<div class="lib-box__btns">
								<?php if (get_field('audio_kniga')): ?>
								<a href="#<?php echo $post->ID; ?>" class="lib-box__btn audio_kniga modal-open">Аудио книга</a>

								<div style="display:none">
									<div class="lib-box-popup" id="<?php echo $post->ID; ?>">
										<audio controls>
											<source src="<?php the_field('audio_kniga');?>" type="audio/mpeg">
											Your browser does not support the audio element.
										</audio>

									</div>
								</div>

								<?php else: ?>
								<div class="lib-box__btn disable">Аудио книга</div>
								<?php endif;?>
								<!--  -->
								<?php if (get_field('videoobzor')): ?>
								<a href="<?php the_field('videoobzor');?>" class="lib-box__btn videoobzor">Видеообзор</a>
								<?php else: ?>
								<div class="lib-box__btn disable">Видеообзор</div>
								<?php endif;?>
								<a href="<?php the_permalink();?>" class="lib-box__btn more">Читать книгу</a>
							</div>
						</div>
					</section>

					<?php endwhile;?>
					<?php endif;?>
					<?php the_posts_pagination();?>
					<?php wp_reset_query();?>


				</div>
			</div>
		</div>




		<div class="books__filter">

			<a href="" class="btn books__filter__reset">Сбросить фильтры</a>
			<br>

			<form action="<?php echo site_url(); ?>/wp-admin/admin-ajax.php" method="POST" id="filter">


				<div class="books__filter__item">

					<h3>Сложность:</h3>

					<?php $terms = get_terms(['taxonomy' => 'complexity', 'hide_empty' => false, 'orderby' => 'name']);?>
					<?php foreach ($terms as $term): ?>

					<label>
						<input type="radio" name="complexity" value="<?php echo $term->term_id; ?>">
						<span>
							<svg height="20" width="20" version="1.1" xmlns="http://www.w3.org/2000/svg"
								xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 360 360"
								style="enable-background:new 0 0 360 360;" xml:space="preserve">
								<path
									d="M303.118,0H56.882C25.516,0,0,25.516,0,56.882v246.236C0,334.484,25.516,360,56.882,360h246.236 C334.484,360,360,334.484,360,303.118V56.882C360,25.516,334.484,0,303.118,0z M322.078,303.118c0,10.454-8.506,18.96-18.959,18.96 H56.882c-10.454,0-18.959-8.506-18.959-18.96V56.882c0-10.454,8.506-18.959,18.959-18.959h246.236 c10.454,0,18.959,8.506,18.959,18.959V303.118z">
								</path>
								<path class="check"
									d="M249.844,106.585c-6.116,0-11.864,2.383-16.19,6.71l-84.719,84.857l-22.58-22.578c-4.323-4.324-10.071-6.706-16.185-6.706 c-6.115,0-11.863,2.382-16.187,6.705c-4.323,4.323-6.703,10.071-6.703,16.185c0,6.114,2.38,11.862,6.703,16.184l38.77,38.77 c4.323,4.324,10.071,6.706,16.186,6.706c6.112,0,11.862-2.383,16.19-6.71L266.03,145.662c8.923-8.926,8.922-23.448,0-32.374 C261.707,108.966,255.958,106.585,249.844,106.585z">
								</path>
							</svg>
							<?php echo $term->name; ?>
						</span>
					</label>

					<?php endforeach;?>

				</div>

				<div class="books__filter__item">

					<h3>Интеоесно детям:</h3>
					<?php $terms = get_terms(['taxonomy' => 'interesting_for_children', 'hide_empty' => false, 'orderby' => 'name']);?>

					<?php foreach ($terms as $term): ?>
					<label>
						<input type="radio" name="interesting_for_children" value="<?php echo $term->term_id; ?>">
						<span>
							<svg height="20" width="20" version="1.1" xmlns="http://www.w3.org/2000/svg"
								xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 360 360"
								style="enable-background:new 0 0 360 360;" xml:space="preserve">
								<path
									d="M303.118,0H56.882C25.516,0,0,25.516,0,56.882v246.236C0,334.484,25.516,360,56.882,360h246.236 C334.484,360,360,334.484,360,303.118V56.882C360,25.516,334.484,0,303.118,0z M322.078,303.118c0,10.454-8.506,18.96-18.959,18.96 H56.882c-10.454,0-18.959-8.506-18.959-18.96V56.882c0-10.454,8.506-18.959,18.959-18.959h246.236 c10.454,0,18.959,8.506,18.959,18.959V303.118z">
								</path>
								<path class="check"
									d="M249.844,106.585c-6.116,0-11.864,2.383-16.19,6.71l-84.719,84.857l-22.58-22.578c-4.323-4.324-10.071-6.706-16.185-6.706 c-6.115,0-11.863,2.382-16.187,6.705c-4.323,4.323-6.703,10.071-6.703,16.185c0,6.114,2.38,11.862,6.703,16.184l38.77,38.77 c4.323,4.324,10.071,6.706,16.186,6.706c6.112,0,11.862-2.383,16.19-6.71L266.03,145.662c8.923-8.926,8.922-23.448,0-32.374 C261.707,108.966,255.958,106.585,249.844,106.585z">
								</path>
							</svg>
							<?php echo $term->name; ?>
						</span>
					</label>
					<?php endforeach;?>
				</div>


				<div class="books__filter__item">
					<h3>Цикл:</h3>
					<?php $terms = get_terms(['taxonomy' => 'loop', 'hide_empty' => false, 'orderby' => 'name']);?>
					<?php foreach ($terms as $term): ?>
					<label>
						<input type="radio" name="loop" value="<?php echo $term->term_id; ?>">
						<span>
							<svg height="20" width="20" version="1.1" xmlns="http://www.w3.org/2000/svg"
								xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 360 360"
								style="enable-background:new 0 0 360 360;" xml:space="preserve">
								<path
									d="M303.118,0H56.882C25.516,0,0,25.516,0,56.882v246.236C0,334.484,25.516,360,56.882,360h246.236 C334.484,360,360,334.484,360,303.118V56.882C360,25.516,334.484,0,303.118,0z M322.078,303.118c0,10.454-8.506,18.96-18.959,18.96 H56.882c-10.454,0-18.959-8.506-18.959-18.96V56.882c0-10.454,8.506-18.959,18.959-18.959h246.236 c10.454,0,18.959,8.506,18.959,18.959V303.118z">
								</path>
								<path class="check"
									d="M249.844,106.585c-6.116,0-11.864,2.383-16.19,6.71l-84.719,84.857l-22.58-22.578c-4.323-4.324-10.071-6.706-16.185-6.706 c-6.115,0-11.863,2.382-16.187,6.705c-4.323,4.323-6.703,10.071-6.703,16.185c0,6.114,2.38,11.862,6.703,16.184l38.77,38.77 c4.323,4.324,10.071,6.706,16.186,6.706c6.112,0,11.862-2.383,16.19-6.71L266.03,145.662c8.923-8.926,8.922-23.448,0-32.374 C261.707,108.966,255.958,106.585,249.844,106.585z">
								</path>
							</svg>
							<?php echo $term->name; ?>
						</span>
					</label>
					<?php endforeach;?>
				</div>

				<button class="btn">Применить фильтр</button>
				<input type="hidden" name="action" value="myfilter">
			</form>




			<a href="" class="btn books__filter__reset">Сбросить фильтры</a>
		</div>
	</div>
</div>






<?php }?>

<?php get_footer();?>